version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5438:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bevy

  backend-express:
    build:
      context: .
      dockerfile: Dockerfile.backend-express
      args:
        - DB_POSTGRES_PORT=5432
        - DB_POSTGRES_USER=postgres
        - DB_POSTGRES_PASSWORD=postgres
        - DB_POSTGRES_DB=bevy
        - DB_POSTGRES_HOST=postgres
        - BACKEND_PORT=4001
    ports:
      - "4001:4001"
    depends_on:
      - postgres
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - SKIP_DB_BUILD=1
        - DB_POSTGRES_PORT=5432
        - DB_POSTGRES_PASSWORD=postgres
        - DB_POSTGRES_USER=postgres
        - DB_POSTGRES_DB=bevy
        - DB_HOST=postgres
        - BACKEND_PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  # bevy_diplomovka:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.bevy
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - backend-express

