[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
dto = { path = "../dto" }
model = { path = "../model" }
axum = { version = "0.7.9" }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5.0", features = ["cors"] }
serde = { version = "1.0.197", features = ["derive"] }
cornucopia_async = "0.6.0"

# Postgres interaction
tokio-postgres = "0.7.7"
postgres-types = "0.2.4"
bb8 = "0.8.3"
bb8-postgres = "0.8.1"
## Connection pooling
deadpool-postgres = "0.12.1"
axum-macros = "0.4.1"

[build-dependencies]
cornucopia = "0.9.0"
postgres = "0.19.9"
