[build]
public_url = "./"
release = true

[serve]
port = 8081
# addresses = ["0.0.0.0"]

[watch]
watch = [
    "./src",
    "./assets",
    "build",
] # Paths to watch. The `build.target`'s parent folder is watched by default.
